name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          curl https://download.docker.com/linux/static/stable/x86_64/docker-28.1.1.tgz --output ./docker.tgz
          tar xzvf docker.tgz
          mv docker/* /usr/bin

          curl -L https://github.com/regclient/regclient/releases/download/v0.8.1/regctl-linux-amd64 > regctl
          chmod 755 regctl
          mv regctl /usr/bin

      - name: Login to FlatArtifacts
        uses: docker/login-action@v3
        with:
          registry: artifacts.flat.software
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push
        run: |
          regctl

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          branch: stable
          manifest-path: com.front.Front.yml
          build-bundle: false

      - name: Build image
        run: |
          flatpak build-bundle ./repo ./image com.front.Front stable --oci
